import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AurumX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body style={{
        background:'#2b2b2b',
        overflowX:'hidden',
        height:'635px',
      }}>
        {/* <Navbar/> */}
        {children}
      </body>
    </html>
  );
}
